# Generated by Django 5.2.10 on 2026-02-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploadfile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("format", models.CharField(max_length=50)),
                ("file_name", models.CharField(max_length=255)),
                ("file_address", models.FileField(upload_to="uploads/")),
                ("file_size", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
